server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/drizzle
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true

  application:
    name: drizzle_backend
